import type { GetRecordParams, ListRecordsParams } from '@/types'
import { stableStringify } from './stable-stringify'

/**
 * Prefix for all **list-style** cache keys for a given table.
 *
 * This is used for bulk invalidation of list results, e.g.:
 *
 * - `client.records.createRecords(...)`
 * - `client.records.updateRecords(...)`
 * - `client.records.deleteRecords(...)`
 *
 * When combined with a store’s `deleteByPrefix`, this prefix will match
 * all keys produced by {@link listKey} for the same base + table.
 *
 * @param baseId - Airtable base ID (e.g. `"appXXXXXXXXXXXXXX"`).
 * @param table - Table ID or table name.
 *
 * @returns A string prefix ending with a trailing colon, e.g.
 *   `"records:list:app123:Tasks:"`.
 *
 * @example
 * ```ts
 * const prefix = tablePrefix('app123', 'Tasks')
 * // "records:list:app123:Tasks:"
 * await cache.deleteByPrefix(prefix)
 * ```
 */
export function tablePrefix(baseId: string, table: string): string {
  return `records:list:${baseId}:${encodeURIComponent(table)}:`
}

/**
 * Prefix for all **record-level** cache keys for a given record.
 *
 * This is used for bulk invalidation of all cached views of a single record,
 * regardless of the exact `GetRecordParams` used (fields, cell format, etc.).
 *
 * When combined with a store’s `deleteByPrefix`, this prefix will match
 * all keys produced by {@link recordKey} for the same base + table + record.
 *
 * @param baseId - Airtable base ID (e.g. `"appXXXXXXXXXXXXXX"`).
 * @param table - Table ID or table name.
 * @param recordId - Airtable record ID (e.g. `"recXXXXXXXXXXXXXX"`).
 *
 * @returns A string prefix ending with a trailing colon, e.g.
 *   `"records:get:app123:Tasks:rec456:"`.
 *
 * @example
 * ```ts
 * const prefix = recordPrefix('app123', 'Tasks', 'rec456')
 * // "records:get:app123:Tasks:rec456:"
 * await cache.deleteByPrefix(prefix)
 * ```
 */
export function recordPrefix(baseId: string, table: string, recordId: string): string {
  return `records:get:${baseId}:${encodeURIComponent(table)}:${recordId}:`
}

/**
 * Full cache key for **list-style** queries (single page).
 *
 * The key is composed of:
 *
 * - base id
 * - table id/name
 * - a stable JSON serialization of {@link ListRecordsParams} using
 *   {@link stableStringify}, so that parameter objects with the same
 *   semantics produce identical keys regardless of key order.
 *
 * This key is used by `client.records.listRecords(...)` when caching is enabled.
 *
 * @param baseId - Airtable base ID.
 * @param table - Table ID or table name.
 * @param params - List parameters excluding `offset` (which is allowed here
 *   but typically managed internally).
 *
 * @returns A deterministic cache key string.
 *
 * @example
 * ```ts
 * const key = listKey('app123', 'Tasks', {
 *   view: 'Grid view',
 *   maxRecords: 50,
 * })
 * // "records:list:app123:Tasks:{...stable json...}"
 * ```
 */
export function listKey(
  baseId: string,
  table: string,
  params?: ListRecordsParams,
): string {
  // Sort params, ensure JSON serialization stability
  return `records:list:${baseId}:${encodeURIComponent(table)}:${stableStringify(params ?? {})}`
}

/**
 * Full cache key for **single-record** fetches (preferred variant).
 *
 * This composes:
 *
 * - {@link recordPrefix} for `(baseId, tableIdOrName, recordId)`
 * - a stable JSON serialization of {@link GetRecordParams} using
 *   {@link stableStringify}
 *
 * The resulting key is fully compatible with {@link recordPrefix}–based
 * invalidation: calling `deleteByPrefix(recordPrefix(...))` will remove
 * all keys produced by this function for the same record.
 *
 * @param baseId - Airtable base ID.
 * @param tableIdOrName - Table ID or table name.
 * @param recordId - Airtable record ID.
 * @param params - Optional {@link GetRecordParams} controlling fields,
 *   cell format, etc.
 *
 * @returns A deterministic cache key for a single record read.
 *
 * @example
 * ```ts
 * const key = recordKey('app123', 'Tasks', 'rec456', {
 *   fields: ['Name', 'Status'],
 * })
 *
 * const prefix = recordPrefix('app123', 'Tasks', 'rec456')
 * // All keys generated by recordKey(...) for this record share that prefix
 * ```
 */
export function recordKey(
  baseId: string,
  tableIdOrName: string,
  recordId: string,
  params?: GetRecordParams,
): string {
  return `${recordPrefix(baseId, tableIdOrName, recordId)}${stableStringify(params ?? {})}`
}
